/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SecretsRouteImport } from './routes/secrets'
import { Route as RuntimeKeysRouteImport } from './routes/runtime-keys'
import { Route as RawJsonRouteImport } from './routes/raw-json'
import { Route as KeysRouteImport } from './routes/keys'
import { Route as EnvironmentsRouteImport } from './routes/environments'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as IndexRouteImport } from './routes/index'

const SecretsRoute = SecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimeKeysRoute = RuntimeKeysRouteImport.update({
  id: '/runtime-keys',
  path: '/runtime-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const RawJsonRoute = RawJsonRouteImport.update({
  id: '/raw-json',
  path: '/raw-json',
  getParentRoute: () => rootRouteImport,
} as any)
const KeysRoute = KeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentsRoute = EnvironmentsRouteImport.update({
  id: '/environments',
  path: '/environments',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/environments': typeof EnvironmentsRoute
  '/keys': typeof KeysRoute
  '/raw-json': typeof RawJsonRoute
  '/runtime-keys': typeof RuntimeKeysRoute
  '/secrets': typeof SecretsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/environments': typeof EnvironmentsRoute
  '/keys': typeof KeysRoute
  '/raw-json': typeof RawJsonRoute
  '/runtime-keys': typeof RuntimeKeysRoute
  '/secrets': typeof SecretsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/environments': typeof EnvironmentsRoute
  '/keys': typeof KeysRoute
  '/raw-json': typeof RawJsonRoute
  '/runtime-keys': typeof RuntimeKeysRoute
  '/secrets': typeof SecretsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagnostics'
    | '/environments'
    | '/keys'
    | '/raw-json'
    | '/runtime-keys'
    | '/secrets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diagnostics'
    | '/environments'
    | '/keys'
    | '/raw-json'
    | '/runtime-keys'
    | '/secrets'
  id:
    | '__root__'
    | '/'
    | '/diagnostics'
    | '/environments'
    | '/keys'
    | '/raw-json'
    | '/runtime-keys'
    | '/secrets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  EnvironmentsRoute: typeof EnvironmentsRoute
  KeysRoute: typeof KeysRoute
  RawJsonRoute: typeof RawJsonRoute
  RuntimeKeysRoute: typeof RuntimeKeysRoute
  SecretsRoute: typeof SecretsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/secrets': {
      id: '/secrets'
      path: '/secrets'
      fullPath: '/secrets'
      preLoaderRoute: typeof SecretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtime-keys': {
      id: '/runtime-keys'
      path: '/runtime-keys'
      fullPath: '/runtime-keys'
      preLoaderRoute: typeof RuntimeKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raw-json': {
      id: '/raw-json'
      path: '/raw-json'
      fullPath: '/raw-json'
      preLoaderRoute: typeof RawJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keys': {
      id: '/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof KeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environments': {
      id: '/environments'
      path: '/environments'
      fullPath: '/environments'
      preLoaderRoute: typeof EnvironmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  EnvironmentsRoute: EnvironmentsRoute,
  KeysRoute: KeysRoute,
  RawJsonRoute: RawJsonRoute,
  RuntimeKeysRoute: RuntimeKeysRoute,
  SecretsRoute: SecretsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
